import { createHash, createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

function keyFromSecret(secret){return createHash('sha256').update(`${secret}:a4print:billing:v1`).digest()}
function encryptJson(value,secret){if(!value||Object.keys(value).length===0)return null;const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',keyFromSecret(secret),iv),raw=Buffer.from(JSON.stringify(value));const enc=Buffer.concat([cipher.update(raw),cipher.final()]),tag=cipher.getAuthTag();return ['v1',iv.toString('base64url'),tag.toString('base64url'),enc.toString('base64url')].join('.')}
function decryptJson(value,secret){if(!value)return{};const [v,iv,tag,data]=String(value).split('.');if(v!=='v1')throw new Error('BILLING_SECRET_STORAGE_INVALID');const d=createDecipheriv('aes-256-gcm',keyFromSecret(secret),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8'))}
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const bool=(v,f=false)=>typeof v==='boolean'?v:f;
const mask=s=>s?`${String(s).slice(0,4)}••••${String(s).slice(-4)}`:'';

export function registerSaasBillingRoutes({app,supabase,requireAdmin,encryptionSecret}){
  if(!app||!supabase||!requireAdmin)return;
  const secret=String(encryptionSecret||process.env.BILLING_ENCRYPTION_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||'');
  if(!secret)console.warn('BILLING_ENCRYPTION_KEY is not configured');

  async function publicConfig(){
    const [{data:settings,error:se},{data:plans,error:pe}]=await Promise.all([
      supabase.from('saas_commerce_settings').select('*').eq('id',true).single(),
      supabase.from('saas_plans').select('code,name,description,monthly_price,annual_price,is_active,is_featured,sort_order,employee_limit,location_limit,monthly_order_limit,features,button_label').eq('is_active',true).order('sort_order')
    ]);if(se)throw se;if(pe)throw pe;return{settings,plans:plans||[]}
  }

  app.get('/api/v1/commerce/public',async(_req,res,next)=>{try{const data=await publicConfig();res.setHeader('Cache-Control','public, max-age=60');res.json({success:true,...data})}catch(e){next(e)}});

  app.get('/api/v1/admin/commerce',requireAdmin,async(_req,res,next)=>{try{
    const [{data:settings,error:se},{data:plans,error:pe},{data:gateway,error:ge},{data:promos,error:pr},{data:subs,error:su},{data:payments,error:pa}]=await Promise.all([
      supabase.from('saas_commerce_settings').select('*').eq('id',true).single(),
      supabase.from('saas_plans').select('*').order('sort_order'),
      supabase.from('saas_gateway_settings').select('*').eq('id',true).single(),
      supabase.from('saas_promo_codes').select('*').order('created_at',{ascending:false}).limit(100),
      supabase.from('saas_subscriptions').select('id,organization_id,customer_id,plan_code,status,billing_period,trial_ends_at,current_period_start,current_period_end,price_locked_until,price_amount,created_at,updated_at').order('created_at',{ascending:false}).limit(100),
      supabase.from('saas_payment_transactions').select('id,subscription_id,organization_id,amount,currency,status,provider,provider_payment_id,description,created_at,paid_at').order('created_at',{ascending:false}).limit(100)
    ]);for(const e of [se,pe,ge,pr,su,pa])if(e)throw e;
    let secretCfg={};try{secretCfg=decryptJson(gateway?.secret_config_enc,secret)}catch{}
    res.json({success:true,settings,plans:plans||[],gateway:{provider:gateway?.provider||'manual',enabled:!!gateway?.enabled,test_mode:gateway?.test_mode!==false,public_config:gateway?.public_config||{},credentials_configured:!!gateway?.secret_config_enc,credential_preview:Object.fromEntries(Object.entries(secretCfg).map(([k,v])=>[k,mask(v)])),webhook_secret_configured:!!gateway?.webhook_secret_enc,updated_at:gateway?.updated_at},promos:promos||[],subscriptions:subs||[],payments:payments||[]});
  }catch(e){next(e)}});

  app.put('/api/v1/admin/commerce/settings',requireAdmin,async(req,res,next)=>{try{const b=req.body||{},payload={id:true,trial_days:Math.max(0,Math.min(365,Math.round(num(b.trial_days,14)))),annual_discount_percent:Math.max(0,Math.min(100,num(b.annual_discount_percent,20))),early_adopter_enabled:bool(b.early_adopter_enabled,true),early_adopter_months:Math.max(0,Math.min(120,Math.round(num(b.early_adopter_months,12)))),hero_badge:String(b.hero_badge||'').slice(0,180),hero_title:String(b.hero_title||'').slice(0,240),hero_text:String(b.hero_text||'').slice(0,1200),pricing_title:String(b.pricing_title||'').slice(0,240),pricing_text:String(b.pricing_text||'').slice(0,1200),free_after_trial:bool(b.free_after_trial,true),currency:String(b.currency||'RUB').slice(0,8).toUpperCase(),updated_at:new Date().toISOString()};const{data,error}=await supabase.from('saas_commerce_settings').upsert(payload).select('*').single();if(error)throw error;res.json({success:true,settings:data})}catch(e){next(e)}});

  app.put('/api/v1/admin/commerce/plans/:code',requireAdmin,async(req,res,next)=>{try{const code=String(req.params.code||'').toUpperCase();const b=req.body||{},payload={code,name:String(b.name||code).slice(0,80),description:String(b.description||'').slice(0,500),monthly_price:Math.max(0,Math.round(num(b.monthly_price))),annual_price:Math.max(0,Math.round(num(b.annual_price))),is_active:bool(b.is_active,true),is_featured:bool(b.is_featured,false),sort_order:Math.round(num(b.sort_order,0)),employee_limit:b.employee_limit==null||b.employee_limit===''?null:Math.max(0,Math.round(num(b.employee_limit))),location_limit:b.location_limit==null||b.location_limit===''?null:Math.max(0,Math.round(num(b.location_limit))),monthly_order_limit:b.monthly_order_limit==null||b.monthly_order_limit===''?null:Math.max(0,Math.round(num(b.monthly_order_limit))),features:typeof b.features==='object'&&b.features?b.features:{},button_label:String(b.button_label||'Выбрать тариф').slice(0,100),updated_at:new Date().toISOString()};const{data,error}=await supabase.from('saas_plans').upsert(payload).select('*').single();if(error)throw error;res.json({success:true,plan:data})}catch(e){next(e)}});

  app.put('/api/v1/admin/commerce/gateway',requireAdmin,async(req,res,next)=>{try{const b=req.body||{},existing=(await supabase.from('saas_gateway_settings').select('*').eq('id',true).single()).data||{};const credentials=typeof b.credentials==='object'&&b.credentials?b.credentials:null,webhookSecret=String(b.webhook_secret||'').trim();const payload={id:true,provider:String(b.provider||existing.provider||'manual').slice(0,50),enabled:bool(b.enabled,existing.enabled||false),test_mode:bool(b.test_mode,existing.test_mode!==false),public_config:typeof b.public_config==='object'&&b.public_config?b.public_config:(existing.public_config||{}),secret_config_enc:credentials&&Object.values(credentials).some(Boolean)?encryptJson(credentials,secret):existing.secret_config_enc||null,webhook_secret_enc:webhookSecret?encryptJson({value:webhookSecret},secret):existing.webhook_secret_enc||null,updated_at:new Date().toISOString()};const{data,error}=await supabase.from('saas_gateway_settings').upsert(payload).select('provider,enabled,test_mode,public_config,secret_config_enc,webhook_secret_enc,updated_at').single();if(error)throw error;res.json({success:true,gateway:{provider:data.provider,enabled:data.enabled,test_mode:data.test_mode,public_config:data.public_config,credentials_configured:!!data.secret_config_enc,webhook_secret_configured:!!data.webhook_secret_enc,updated_at:data.updated_at}})}catch(e){next(e)}});

  app.post('/api/v1/admin/commerce/gateway/test',requireAdmin,async(_req,res,next)=>{try{const{data:g,error}=await supabase.from('saas_gateway_settings').select('*').eq('id',true).single();if(error)throw error;let creds={};try{creds=decryptJson(g.secret_config_enc,secret)}catch{};const required={manual:[],yookassa:['shop_id','secret_key'],tbank:['terminal_key','password'],cloudpayments:['public_id','api_secret'],robokassa:['merchant_login','password1']}[g.provider]||[];const missing=required.filter(k=>!creds[k]);if(missing.length)return res.status(409).json({success:false,error:'GATEWAY_CREDENTIALS_INCOMPLETE',message:`Не заполнено: ${missing.join(', ')}`});res.json({success:true,provider:g.provider,enabled:g.enabled,test_mode:g.test_mode,credentials_configured:true,message:g.provider==='manual'?'Ручной режим готов.':'Конфигурация шлюза заполнена. Боевой запрос будет проверен при подключении checkout/webhook.'})}catch(e){next(e)}});

  app.post('/api/v1/admin/commerce/promos',requireAdmin,async(req,res,next)=>{try{const b=req.body||{},code=String(b.code||'').trim().toUpperCase().replace(/[^A-ZА-Я0-9_-]/g,'').slice(0,40);if(!code)return res.status(400).json({success:false,error:'PROMO_CODE_REQUIRED'});const payload={code,description:String(b.description||'').slice(0,300),discount_type:b.discount_type==='fixed'?'fixed':'percent',discount_value:Math.max(0,num(b.discount_value)),active:bool(b.active,true),max_uses:b.max_uses==null||b.max_uses===''?null:Math.max(1,Math.round(num(b.max_uses))),starts_at:b.starts_at||null,ends_at:b.ends_at||null,applies_to:Array.isArray(b.applies_to)?b.applies_to:[],updated_at:new Date().toISOString()};const{data,error}=await supabase.from('saas_promo_codes').upsert(payload).select('*').single();if(error)throw error;res.json({success:true,promo:data})}catch(e){next(e)}});
  app.delete('/api/v1/admin/commerce/promos/:code',requireAdmin,async(req,res,next)=>{try{const{error}=await supabase.from('saas_promo_codes').delete().eq('code',String(req.params.code).toUpperCase());if(error)throw error;res.json({success:true})}catch(e){next(e)}});

  app.patch('/api/v1/admin/commerce/subscriptions/:id',requireAdmin,async(req,res,next)=>{try{const b=req.body||{},allowed=['plan_code','status','billing_period','trial_ends_at','current_period_end','price_locked_until','price_amount'];const patch={updated_at:new Date().toISOString()};for(const k of allowed)if(k in b)patch[k]=b[k]===''?null:b[k];const{data,error}=await supabase.from('saas_subscriptions').update(patch).eq('id',req.params.id).select('*').single();if(error)throw error;res.json({success:true,subscription:data})}catch(e){next(e)}});
}