import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { createClient } from '@supabase/supabase-js';
import { syncMoySkladCatalog, fetchMoySkladStock, createRetailSale } from './moysklad.js';
const app=express(),port=Number(process.env.PORT||3000);app.use(cors({origin:process.env.CORS_ORIGIN?.split(',').map(v=>v.trim()).filter(Boolean)||true}));app.use(express.json({limit:'1mb'}));
const supabaseUrl=process.env.SUPABASE_URL,supabaseKey=process.env.SUPABASE_SERVICE_ROLE_KEY,publishableKey=process.env.SUPABASE_PUBLISHABLE_KEY;const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey,{auth:{autoRefreshToken:false,persistSession:false}}):null;
app.get('/api/v1/health',(_q,r)=>r.json({success:true,service:'a4print-hub-api',status:'ok',databaseConfigured:Boolean(supabase),moyskladConfigured:Boolean(process.env.MOYSKLAD_TOKEN)}));
async function requireAdmin(req,res,next){try{if(!supabaseUrl||!publishableKey)return res.status(503).json({success:false,error:'AUTH_NOT_CONFIGURED'});const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({success:false,error:'AUTH_REQUIRED'});const c=createClient(supabaseUrl,publishableKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{autoRefreshToken:false,persistSession:false}});const {data:{user},error}=await c.auth.getUser(token);if(error||!user)return res.status(401).json({success:false,error:'INVALID_SESSION'});const {data:isAdmin,error:roleError}=await c.rpc('has_role',{required_role:'ADMIN'});if(roleError)throw roleError;if(!isAdmin)return res.status(403).json({success:false,error:'ADMIN_REQUIRED'});req.authUser=user;next()}catch(e){next(e)}}
const msReady=(res)=>{if(!supabase){res.status(503).json({success:false,error:'DATABASE_NOT_CONFIGURED'});return false}if(!process.env.MOYSKLAD_TOKEN){res.status(503).json({success:false,error:'MOYSKLAD_NOT_CONFIGURED'});return false}return true};
app.post('/api/v1/integrations/moysklad/sync',requireAdmin,async(req,res,next)=>{try{if(!msReady(res))return;const {data:org,error}=await supabase.from('organizations').select('id').eq('code','A4PRINT').single();if(error)throw error;const result=await syncMoySkladCatalog({supabase,token:process.env.MOYSKLAD_TOKEN,organizationId:org.id});res.json({success:true,...result})}catch(e){next(e)}});
app.get('/api/v1/integrations/moysklad/stock',requireAdmin,async(req,res,next)=>{try{if(!msReady(res))return;const stock=await fetchMoySkladStock(process.env.MOYSKLAD_TOKEN);res.json({success:true,stock})}catch(e){next(e)}});
app.post('/api/v1/pos/sale',requireAdmin,async(req,res,next)=>{try{if(!msReady(res))return;const input=req.body||{};if(!Array.isArray(input.items)||!input.items.length)return res.status(400).json({success:false,error:'EMPTY_CART'});const ids=input.items.map(x=>x.id);const {data:rows,error}=await supabase.from('catalog_items').select('id,name,sale_price,external_id,external_href,item_type').in('id',ids);if(error)throw error;const byId=new Map((rows||[]).map(x=>[x.id,x]));const items=input.items.map(x=>{const g=byId.get(x.id);if(!g)throw new Error('Товар не найден: '+x.id);return{id:g.id,name:g.name,qty:Math.max(1,Number(x.qty||1)),price:Number(x.price??g.sale_price??0),external_href:g.external_href,external_type:g.external_href?.split('/').slice(-2,-1)[0]||'product'}});const sale=await createRetailSale({token:process.env.MOYSKLAD_TOKEN,items,paymentMethod:input.payment_method});res.json({success:true,moysklad:{id:sale.id,name:sale.name,href:sale.meta?.href},sum:Number(sale.sum||0)/100})}catch(e){next(e)}});
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({success:false,error:'INTERNAL_SERVER_ERROR',message:err.message})});app.listen(port,()=>console.log(`A4PRINT HUB API listening on port ${port}`));
