(()=>{
  'use strict';
  if(window.__A4_KASSA_NETWORK_SAFETY__)return;
  window.__A4_KASSA_NETWORK_SAFETY__=true;

  const nativeFetch=window.fetch.bind(window);
  const cfg=window.A4PRINT_CONFIG||{};
  const PRIMARY='https://api.a4print-hub.ru';
  const RENDER='https://a4print-hub-api.onrender.com';
  const configured=String(cfg.apiBaseUrl||'').replace(/\/$/,'');
  const KNOWN=[PRIMARY,configured,RENDER].filter((v,i,a)=>v&&a.indexOf(v)===i);
  const READ_TIMEOUT=6500;
  const HEAVY_READ_TIMEOUT=30000;
  const WRITE_TIMEOUT=14000;
  const RETURN_WRITE_TIMEOUT=60000;
  const STAGGER_MS=250;

  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

  function parse(input,init={}){
    try{
      const req=new Request(input,init);
      const url=new URL(req.url);
      return KNOWN.includes(url.origin)?{req,url,method:req.method.toUpperCase()}:null;
    }catch{return null}
  }

  function routedUrl(url,base){
    const target=new URL(url.href);
    const b=new URL(base);
    target.protocol=b.protocol;
    target.host=b.host;
    return target.href;
  }

  function isHeavyRead(url){
    const p=url.pathname;
    return /\/api\/v1\/pos\/cash-balance(?:\/|$)/.test(p)
      || /\/api\/v1\/pos\/shift(?:\/|$)/.test(p);
  }

  function writeTimeoutFor(url){
    return /\/api\/v1\/pos\/returns\/?$/.test(url.pathname)?RETURN_WRITE_TIMEOUT:WRITE_TIMEOUT;
  }

  async function one(req,url,base,timeout){
    const controller=new AbortController();
    const timer=setTimeout(()=>controller.abort(),timeout);
    try{
      const routed=new Request(routedUrl(url,base),req);
      return await nativeFetch(routed,{signal:controller.signal,cache:'no-store'});
    }finally{clearTimeout(timer)}
  }

  function routeOrder(url){
    const current=url.origin;
    return [current,PRIMARY,configured,RENDER].filter((v,i,a)=>v&&a.indexOf(v)===i);
  }

  // Heavy POS reads can fan out into several MoySklad calls. Racing the same
  // request through API aliases duplicates that work and can create its own
  // rate-limit/timeout storm, so use one route at a time for these endpoints.
  async function readHeavy(req,url){
    const routes=routeOrder(url);
    let lastError=null;
    let clientResponse=null;
    for(const base of routes){
      try{
        const response=await one(req.clone(),url,base,HEAVY_READ_TIMEOUT);
        if(response.ok)return response;
        if(response.status<500)return response;
        clientResponse=response;
        lastError=new Error(`HTTP ${response.status}`);
      }catch(error){lastError=error}
    }
    if(clientResponse)return clientResponse;
    throw lastError||new Error('API_UNREACHABLE');
  }

  // Short reads are safe to race. We prefer a successful backend response
  // instead of immediately trusting a 401/403 generated by an ISP/VPN/CDN edge.
  async function readWithFailover(req,url){
    if(isHeavyRead(url))return readHeavy(req,url);
    const routes=routeOrder(url);
    return await new Promise((resolve,reject)=>{
      let pending=routes.length;
      let settled=false;
      let clientResponse=null;
      let lastError=null;
      routes.forEach((base,index)=>{
        (async()=>{
          if(index)await sleep(STAGGER_MS*index);
          try{
            const response=await one(req.clone(),url,base,READ_TIMEOUT);
            if(settled)return;
            if(response.ok){settled=true;resolve(response);return}
            if(response.status<500&&!clientResponse)clientResponse=response;
            else lastError=new Error(`HTTP ${response.status}`);
          }catch(error){lastError=error}
          finally{
            pending--;
            if(!settled&&pending===0){
              settled=true;
              if(clientResponse)resolve(clientResponse);
              else reject(lastError||new Error('API_UNREACHABLE'));
            }
          }
        })();
      });
    });
  }

  function isAuthWrite(url){
    const p=url.pathname;
    return /\/api\/v1\/mobile\/auth\/(?:password|refresh)\/?$/.test(p)
      || /\/api\/v1\/supabase\/auth\/v1\//.test(p);
  }

  function isIdempotentWrite(url){
    const p=url.pathname;
    return isAuthWrite(url)
      || /\/api\/v1\/pos\/shift\/open\/?$/.test(p)
      || /\/api\/v1\/pos\/sale\/?$/.test(p);
  }

  async function writeWithFailover(req,url){
    const routes=routeOrder(url);
    const allowFallback=isIdempotentWrite(url);
    const authWrite=isAuthWrite(url);
    const timeout=writeTimeoutFor(url);
    let lastError=null;
    let clientResponse=null;

    for(let i=0;i<routes.length;i++){
      try{
        const response=await one(req.clone(),url,routes[i],timeout);
        if(response.ok)return response;
        if(response.status<500){
          clientResponse=clientResponse||response;
          if(authWrite&&i<routes.length-1)continue;
          return response;
        }
        lastError=new Error(`HTTP ${response.status}`);
        if(!allowFallback)return response;
      }catch(error){
        lastError=error;
        if(!allowFallback)throw error;
      }
    }

    if(clientResponse)return clientResponse;
    throw lastError||new Error('API_UNREACHABLE');
  }

  window.fetch=async function a4SafeFetch(input,init={}){
    const info=parse(input,init);
    if(!info)return nativeFetch(input,init);
    const {req,url,method}=info;
    if(method==='GET'||method==='HEAD')return readWithFailover(req,url);
    return writeWithFailover(req,url);
  };
})();
