-- Automated non-destructive end-to-end self-test for A4PRINT HUB.
-- Creates temporary customer/order/chat data, verifies chat notification wiring,
-- verifies Push prerequisites, cleans all temporary rows, and logs the result.

create table if not exists public.system_self_test_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz not null default now(),
  status text not null check (status in ('PASS','FAIL')),
  details jsonb not null default '{}'::jsonb
);

alter table public.system_self_test_runs enable row level security;
revoke all on public.system_self_test_runs from anon, authenticated;

create or replace function public.run_system_e2e_self_test()
returns jsonb
language plpgsql
security definer
set search_path = public, vault, net, pg_temp
as $$
declare
  v_started timestamptz := clock_timestamp();
  v_sender uuid := gen_random_uuid();
  v_recipient uuid := gen_random_uuid();
  v_customer uuid := gen_random_uuid();
  v_order uuid := gen_random_uuid();
  v_room uuid := gen_random_uuid();
  v_message uuid := gen_random_uuid();
  v_order_number bigint;
  v_notification_count integer := 0;
  v_catalog_priced integer := 0;
  v_push_subscriptions integer := 0;
  v_push_secret boolean := false;
  v_push_trigger boolean := false;
  v_customer_ok boolean := false;
  v_order_ok boolean := false;
  v_chat_ok boolean := false;
  v_notification_ok boolean := false;
  v_status text := 'FAIL';
  v_details jsonb;
  v_error text;
begin
  perform pg_advisory_xact_lock(hashtext('a4print_hub_system_e2e_self_test'));

  begin
    insert into public.users(id, full_name, email, is_active)
    values
      (v_sender, '[SYSTEM TEST] Sender', 'system-test-sender@invalid.local', true),
      (v_recipient, '[SYSTEM TEST] Recipient', 'system-test-recipient@invalid.local', true);

    insert into public.customers(id, full_name, email, notes)
    values (v_customer, '[SYSTEM TEST] Customer', 'system-test-customer@invalid.local', 'Temporary automated self-test row');
    select exists(select 1 from public.customers where id=v_customer and full_name='[SYSTEM TEST] Customer') into v_customer_ok;

    insert into public.orders(id, business_unit, customer_id, assigned_to, status, total, source, model_name, internal_comment, partner_direction)
    values (v_order, 'A4_PRINT'::business_unit, v_customer, v_sender, 'NEW'::order_status, 123.45, 'SYSTEM_E2E_TEST', '[SYSTEM TEST] Service', 'Temporary automated self-test row', 'NONE')
    returning order_number into v_order_number;
    select exists(select 1 from public.orders where id=v_order and customer_id=v_customer and total=123.45) into v_order_ok;

    insert into public.chat_rooms(id, name, is_group, order_id, direct_key)
    values (v_room, '[SYSTEM TEST] Room', false, v_order, 'system-e2e:' || v_room::text);
    insert into public.chat_members(room_id,user_id) values (v_room,v_sender),(v_room,v_recipient);
    insert into public.messages(id,room_id,sender_id,body)
    values (v_message,v_room,v_sender,'[SYSTEM TEST] Message delivery check');

    select exists(select 1 from public.messages where id=v_message and room_id=v_room) into v_chat_ok;
    select count(*) into v_notification_count
    from public.notifications
    where user_id=v_recipient and type='CHAT_MESSAGE' and entity_type='chat_room' and entity_id=v_room;
    v_notification_ok := v_notification_count = 1;

    select count(*) into v_catalog_priced from public.catalog_items where is_active=true and coalesce(sale_price,0)>0;
    select count(*) into v_push_subscriptions from public.push_subscriptions where is_active=true;

    select exists(
      select 1 from pg_trigger
      where tgrelid='public.messages'::regclass
        and tgname='trg_chat_push_after_message'
        and not tgisinternal
    ) into v_push_trigger;

    begin
      select exists(
        select 1 from vault.decrypted_secrets
        where name='a4_chat_push_hook_secret' and nullif(decrypted_secret,'') is not null
      ) into v_push_secret;
    exception when others then
      v_push_secret := false;
    end;

    v_status := case when v_customer_ok and v_order_ok and v_chat_ok and v_notification_ok and v_catalog_priced > 0 and v_push_trigger then 'PASS' else 'FAIL' end;

    delete from public.notifications where user_id in (v_sender,v_recipient) and entity_id=v_room;
    delete from public.chat_rooms where id=v_room;
    delete from public.orders where id=v_order;
    delete from public.customers where id=v_customer;
    delete from public.users where id in (v_sender,v_recipient);

    v_details := jsonb_build_object(
      'customer_create', v_customer_ok,
      'order_create', v_order_ok,
      'chat_message_create', v_chat_ok,
      'chat_notification_create', v_notification_ok,
      'notification_count', v_notification_count,
      'catalog_priced_items', v_catalog_priced,
      'active_push_subscriptions', v_push_subscriptions,
      'push_trigger_present', v_push_trigger,
      'push_hook_secret_present', v_push_secret,
      'cleanup', true,
      'order_number', v_order_number
    );
  exception when others then
    v_error := sqlerrm;
    v_status := 'FAIL';
    v_details := jsonb_build_object('error', v_error, 'cleanup', true);
  end;

  insert into public.system_self_test_runs(started_at,finished_at,status,details)
  values(v_started,clock_timestamp(),v_status,v_details);

  return jsonb_build_object('status',v_status,'started_at',v_started,'finished_at',clock_timestamp(),'details',v_details);
end;
$$;

revoke all on function public.run_system_e2e_self_test() from public, anon, authenticated;
grant execute on function public.run_system_e2e_self_test() to service_role;

create index if not exists system_self_test_runs_started_at_idx on public.system_self_test_runs(started_at desc);

do $$
declare v_jobid bigint;
begin
  select jobid into v_jobid from cron.job where jobname='a4print-hub-system-e2e-daily' limit 1;
  if v_jobid is not null then perform cron.unschedule(v_jobid); end if;
  perform cron.schedule('a4print-hub-system-e2e-daily','23 3 * * *',$cron$select public.run_system_e2e_self_test();$cron$);
end $$;
