(()=>{const map={
'index.html':['Главная панель','Здесь собраны основные показатели HUB: новые заказы, активные работы, готовность и остатки. Используйте панель как точку контроля и перехода в рабочие разделы.','#login'],
'manager.html':['Рабочий стол менеджера','Создавайте предварительные заказы: выберите клиента и услугу, заполните параметры, проверьте цену, комментарий и файлы, затем убедитесь, что заказ появился в общем списке.','#manager'],
'orders.html':['Заказы','Проверяйте состав, сумму, параметры и файлы заказа. Меняйте статус только по фактическому этапу: Новый → Подтверждён → В работе → Готов → Завершён.','#orders'],
'customers.html':['Клиенты','Сначала ищите клиента в базе, чтобы не создавать дубль. Храните заказы одного клиента в одной карточке.','#customers'],
'partners.html':['Партнёры','Здесь создаются партнёры, настраиваются партнёрские цены и оформляются заказы A4PRINT партнёру по его собственному прайсу.','#partners'],
'warehouse.html':['Склад и номенклатура','Оформляйте реальные движения материалов: приход, продажу, списание и производство. Не корректируйте остатки без основания.','#warehouse'],
'production.html':['Производство','Перед началом проверьте параметры и макеты. Меняйте статус по фактическому выполнению и фиксируйте проблему, если работа остановлена.','#production'],
'messages.html':['Сообщения','Используйте чат для оперативной коммуникации. Критичные сведения по заказу дублируйте в карточке самого заказа.','#messages'],
'users.html':['Пользователи','Администратор создаёт сотрудников и назначает минимально необходимые роли. Для кассы используйте POS_OPERATOR.','#users'],
'operators.html':['Операторы POS','Создавайте и управляйте кассирами. Проверяйте активность оператора и корректность роли POS_OPERATOR.','#users'],
'documents.html':['Документы','Храните рабочие документы, связанные с операциями HUB, и проверяйте привязку к нужному клиенту или заказу.','#orders'],
'payments.html':['Оплаты','Сверяйте оплату с конкретным заказом и не меняйте финансовые данные без подтверждения фактической операции.','#orders'],
'reports.html':['Отчёты','Используйте отчёты для контроля работы. Перед выводами проверяйте выбранный период и фильтры.','#orders'],
'settings.html':['Настройки','Изменяйте системные параметры только осознанно. После изменения проверяйте работу соответствующего модуля.','#users'],
'help.html':['Инструкция','Полное руководство по работе с HUB, POS и кабинетом партнёра.','']};
function init(){const page=location.pathname.split('/').pop()||'index.html',x=map[page]||['Помощь по странице','Откройте полное руководство A4PRINT HUB для пошаговой инструкции.',''];if(document.getElementById('a4-help-btn'))return;const css=document.createElement('style');css.textContent='.a4-help-btn{position:fixed;right:18px;bottom:76px;z-index:9998;width:46px;height:46px;border:0;border-radius:50%;background:#0f172a;color:#fff;font:900 20px Arial;cursor:pointer;box-shadow:0 8px 24px rgba(15,23,42,.25)}.a4-help-pop{position:fixed;right:18px;bottom:132px;z-index:9999;width:min(380px,calc(100vw - 36px));background:white;border:1px solid #e2e8f0;border-radius:16px;padding:16px;box-shadow:0 18px 45px rgba(15,23,42,.22);display:none}.a4-help-pop.open{display:block}.a4-help-pop h3{margin:0 0 8px}.a4-help-pop p{margin:0 0 12px;color:#475569;line-height:1.45}.a4-help-pop a{display:inline-block;padding:9px 12px;background:#2563eb;color:#fff;text-decoration:none;border-radius:9px;font-weight:800}.a4-help-close{float:right;background:transparent!important;color:#64748b!important;padding:0!important;font-size:18px!important}';document.head.appendChild(css);const b=document.createElement('button');b.id='a4-help-btn';b.className='a4-help-btn';b.type='button';b.textContent='?';b.title='Помощь по этой странице';const p=document.createElement('div');p.className='a4-help-pop';p.innerHTML=`<button class="a4-help-close" type="button">×</button><h3>${x[0]}</h3><p>${x[1]}</p><a href="./help.html${x[2]}">Открыть подробную инструкцию</a>`;b.onclick=()=>p.classList.toggle('open');p.querySelector('.a4-help-close').onclick=()=>p.classList.remove('open');document.body.append(p,b)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()})();