import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const config=window.A4PRINT_CONFIG||{},SUPABASE_URL=config.supabaseUrl||'https://qgakliolffnwkymoqvzn.supabase.co',SUPABASE_PUBLISHABLE_KEY=config.supabasePublishableKey||'';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),form=document.getElementById('form'),submit=document.getElementById('submit'),error=document.getElementById('error'),recoveryBox=document.getElementById('recoveryBox'),recoveryEmail=document.getElementById('recoveryEmail'),recoveryError=document.getElementById('recoveryError'),recoverySuccess=document.getElementById('recoverySuccess'),sendRecovery=document.getElementById('sendRecovery');
let authSettings=null;
function showError(message){error.textContent=message;error.style.display='block'}function resetRecoveryMessages(){recoveryError.style.display='none';recoverySuccess.style.display='none';recoveryError.textContent='';recoverySuccess.textContent=''}
function providerName(provider){if(provider==='google')return'Google';if(provider==='custom:yandex')return'Яндекс';if(provider==='custom:mailru')return'Mail.ru';return provider}
async function loadAuthSettings(){if(authSettings)return authSettings;try{const r=await fetch(`${SUPABASE_URL}/auth/v1/settings`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY}});if(!r.ok)return null;authSettings=await r.json();return authSettings}catch{return null}}
function providerEnabled(settings,provider){const ext=settings?.external;if(!ext||typeof ext!=='object')return null;if(Object.prototype.hasOwnProperty.call(ext,provider))return Boolean(ext[provider]);if(provider.startsWith('custom:')){const key=provider.slice(7);if(Object.prototype.hasOwnProperty.call(ext,key))return Boolean(ext[key])}return null}
async function routeByProfile(){const{data,error:e}=await supabase.rpc('get_my_staff_profile');if(e)throw e;const st=data?.status;if(st==='ACTIVE'){const roles=new Set((data.roles||[]).map(r=>r.name));location.replace(roles.has('POS_OPERATOR')&&roles.size===1?'../pos/index.html':'./index.html');return}if(st==='PENDING'||st==='REJECTED'){location.replace('./pending.html');return}location.replace('./register.html')}
document.getElementById('showRecovery').onclick=()=>{resetRecoveryMessages();recoveryEmail.value=document.getElementById('email').value.trim();recoveryBox.classList.add('open');recoveryEmail.focus()};document.getElementById('hideRecovery').onclick=()=>recoveryBox.classList.remove('open');sendRecovery.onclick=async()=>{resetRecoveryMessages();const email=recoveryEmail.value.trim();if(!email){recoveryError.textContent='Введите email.';recoveryError.style.display='block';return}sendRecovery.disabled=true;try{const redirectTo=new URL('./reset-password.html',location.href).href;const{error:e}=await supabase.auth.resetPasswordForEmail(email,{redirectTo});if(e)throw e;recoverySuccess.textContent='Ссылка отправлена. Откройте письмо и перейдите по ней.';recoverySuccess.style.display='block'}catch(e){recoveryError.textContent=e?.message||'Не удалось отправить письмо.';recoveryError.style.display='block'}finally{sendRecovery.disabled=false}};
for(const b of document.querySelectorAll('[data-provider]'))b.onclick=async()=>{error.style.display='none';b.disabled=true;try{if(!SUPABASE_PUBLISHABLE_KEY)throw new Error('Не задан Publishable Key Supabase.');const provider=b.dataset.provider,settings=await loadAuthSettings(),enabled=providerEnabled(settings,provider);if(enabled===false)throw new Error(`${providerName(provider)} пока не подключён в настройках входа A4PRINT HUB. Используйте вход по email или обратитесь к администратору.`);const redirectTo=new URL('./login.html?oauth=1',location.href).href;const{error:e}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo}});if(e)throw e}catch(e){showError(e?.message||'Не удалось открыть авторизацию.');b.disabled=false}};
form.addEventListener('submit',async event=>{event.preventDefault();error.style.display='none';submit.disabled=true;submit.textContent='Входим…';try{await supabase.auth.signOut({scope:'local'}).catch(()=>{});const{error:e}=await supabase.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});if(e)throw e;submit.textContent='Проверяем доступ…';await routeByProfile()}catch(e){showError(e?.message||'Не удалось выполнить вход.')}finally{submit.disabled=false;submit.textContent='Войти'}});
(async()=>{await loadAuthSettings();if(new URLSearchParams(location.search).get('oauth')!=='1')return;try{const{data:{session},error:e}=await supabase.auth.getSession();if(e)throw e;if(session)await routeByProfile()}catch(e){showError(e?.message||'Не удалось завершить вход.')}})();
