import { supabase } from './guard.js';
const id = new URLSearchParams(location.search).get('id');
const $ = x => document.getElementById(x);
const labels={NEW:'Новый',CONFIRMED:'Подтверждён',IN_PROGRESS:'В работе',READY:'Готов',COMPLETED:'Завершён',ON_HOLD:'Приостановлен',CANCELLED:'Отменён'};
function esc(v=''){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
let currentOrder=null,currentStaffId=null;
async function resolveStaff(){const{data:{session}}=await supabase.auth.getSession();if(!session)return;const{data}=await supabase.from('users').select('id').eq('auth_user_id',session.user.id).maybeSingle();currentStaffId=data?.id||null;}
function render(o){
  currentOrder=o;
  $('title').textContent=`Заказ №${o.order_number??'—'}`;
  $('subtitle').textContent=o.business_unit==='3D_ARTPRINT'?'3D-ARTPRINT':o.business_unit==='A4_PRINT'?'А4-Принт':'Общий';
  $('status').textContent=labels[o.status]||o.status;
  const c=o.customers||{},requester=o.requester||{},executor=o.executor||{},pu=o.partner_users||{};
  const partner=o.partner_id?requester:(o.fulfillment_partner_id?executor:null);
  const partnerRole=o.partner_id?'Партнёр заказал у нас':'Мы заказали у партнёра';
  const isPartner=!!partner;
  const partnerBlock=isPartner?`<div style="padding:14px;border:1px solid #bbf7d0;background:#f0fdf4;border-radius:12px"><h3 style="margin-top:0">🤝 ${esc(partnerRole)}</h3><b>${esc(partner.name||'Партнёр')}</b><div style="color:#64748b;margin-top:4px">${esc(pu.full_name||partner.contact_name||'')}${partner.phone?` · ${esc(partner.phone)}`:''}${partner.email?` · ${esc(partner.email)}`:''}</div><div style="margin-top:8px">Скидка: ${Number(partner.discount_percent||0)}% · отсрочка: ${Number(partner.payment_terms_days||0)} дн.</div></div>`:'';
  $('details').innerHTML=`<div style="display:grid;gap:20px">${partnerBlock}<div><h3>${o.partner_id?'Заказчик':o.fulfillment_partner_id?'Исполнитель':'Клиент'}</h3><b>${esc(isPartner?(partner.name||'Партнёр'):(c.full_name||c.company_name||'Не указан'))}</b><div style="color:#64748b">${isPartner?esc(partner.phone||partner.email||''):esc(c.phone||'')}${!isPartner&&c.email?` · ${esc(c.email)}`:''}</div></div><div><h3>Модель / работа</h3><b>${esc(o.model_name||o.source||'—')}</b>${o.model_url?`<div><a href="${esc(o.model_url)}" target="_blank" rel="noopener">🔗 Открыть модель</a></div>`:''}</div><div><h3>Позиции</h3>${(o.order_items||[]).map(i=>`<div style="padding:10px 0;border-bottom:1px solid #e5e7eb"><b>${esc(i.name)}</b> × ${i.quantity}<span style="float:right">${Number(i.total_price||0).toLocaleString('ru-RU')} ₽</span>${i.parameters?.details?`<div style="color:#64748b;font-size:13px;margin-top:5px">${esc(i.parameters.details)}</div>`:''}</div>`).join('')||'—'}</div><div><h3>Стоимость</h3><strong style="font-size:26px">${Number(o.total||0).toLocaleString('ru-RU')} ₽</strong></div><div><h3>Комментарий заказчика</h3><div>${esc(o.customer_comment||'Нет')}</div></div>${o.partner_id?`<div><h3>Сообщения партнёру</h3><div id="partnerMessages" style="display:grid;gap:8px;margin-bottom:10px"></div><textarea id="partnerReply" placeholder="Это сообщение увидит партнёр" style="width:100%;min-height:75px;padding:10px"></textarea><button id="sendPartnerReply" style="margin-top:8px">Отправить партнёру</button></div>`:''}<div><h3>Внутренний комментарий</h3><textarea id="internalComment" style="width:100%;min-height:90px;padding:10px">${esc(o.internal_comment||'')}</textarea><button id="saveComment" style="margin-top:8px">Сохранить комментарий</button></div><div><button id="productionBtn">🏭 Передать в производство</button></div></div>`;
  $('history').innerHTML=(o.order_status_history||[]).map(h=>`<div style="padding:10px 0;border-bottom:1px solid #e5e7eb"><b>${labels[h.new_status]||h.new_status}</b><div style="color:#64748b;font-size:13px">${new Date(h.created_at).toLocaleString('ru-RU')} ${esc(h.comment||'')}</div></div>`).join('')||'<div class="empty">История пока пуста</div>';
  $('saveComment').onclick=saveComment;$('productionBtn').onclick=sendProduction;
  if(o.partner_id){$('sendPartnerReply').onclick=sendPartnerReply;renderPartnerMessages(o.partner_order_messages||[]);}
}
function renderPartnerMessages(rows){const box=$('partnerMessages');if(!box)return;box.innerHTML=rows.map(m=>`<div style="padding:9px 11px;border-radius:10px;background:${m.sender_type==='PARTNER'?'#f8fafc':'#eff6ff'}"><b>${m.sender_type==='PARTNER'?'Партнёр':'A4PRINT'}</b><div>${esc(m.body)}</div><small style="color:#64748b">${new Date(m.created_at).toLocaleString('ru-RU')}</small></div>`).join('')||'<div style="color:#94a3b8">Сообщений пока нет</div>'}
async function load(){if(!id){$('details').innerHTML='<div class="empty">Не указан ID заказа</div>';return}const query='*,customers(*),requester:partners!orders_partner_id_fkey(*),executor:partners!orders_fulfillment_partner_id_fkey(*),partner_users(*),order_items(*),order_status_history(*),partner_order_messages(*)';const {data,error}=await supabase.from('orders').select(query).eq('id',id).single();if(error){$('details').innerHTML=`<div class="empty">Ошибка: ${esc(error.message)}</div>`;return}render(data)}
async function saveComment(){const {error}=await supabase.from('orders').update({internal_comment:$('internalComment').value,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else alert('Комментарий сохранён')}
async function sendPartnerReply(){const body=$('partnerReply').value.trim();if(!body)return;const{error}=await supabase.from('partner_order_messages').insert({order_id:id,staff_user_id:currentStaffId,sender_type:'STAFF',body});if(error)return alert(error.message);$('partnerReply').value='';await load()}
async function changeStatus(status){const {data:old,error:e}=await supabase.from('orders').select('status').eq('id',id).single();if(e)return alert(e.message);const {error}=await supabase.from('orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await supabase.from('order_status_history').insert({order_id:id,old_status:old.status,new_status:status,comment:'Изменено из панели управления'});load()}
async function sendProduction(){const {data:o,error:e}=await supabase.from('orders').select('order_number,model_name,status').eq('id',id).single();if(e)return alert(e.message);const {data:exists}=await supabase.from('production_jobs').select('id').eq('order_id',id).limit(1);if(exists?.length)return alert('Производственное задание уже создано');const {error}=await supabase.from('production_jobs').insert({order_id:id,title:`Заказ №${o.order_number}${o.model_name?' — '+o.model_name:''}`,status:'NEW'});if(error)return alert(error.message);if(o.status==='NEW')await changeStatus('CONFIRMED');alert('Заказ передан в производство')}
document.querySelectorAll('[data-status]').forEach(btn=>btn.onclick=()=>changeStatus(btn.dataset.status));await resolveStaff();load();
