import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.A4PRINT_CONFIG||{};
const supabase=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);
const $=id=>document.getElementById(id),error=$('error'),success=$('success'),submit=$('submit');
function showError(m){error.textContent=m;error.style.display='block';success.style.display='none'}
function showSuccess(m){success.textContent=m;success.style.display='block';error.style.display='none'}
async function goByProfile(){const{data,error}=await supabase.rpc('get_my_staff_profile');if(error)throw error;const st=data?.status;if(st==='ACTIVE')return location.replace('./profile.html');if(st==='PENDING'||st==='REJECTED')return location.replace('./pending.html');return data}
async function submitRequest(provider){const meta=(await supabase.auth.getUser()).data.user?.user_metadata||{};const fullName=$('fullName')?.value.trim()||meta.full_name||meta.name||'';const phone=$('phone')?.value.trim()||meta.phone||'';const{error}=await supabase.rpc('submit_staff_registration',{p_full_name:fullName||null,p_phone:phone||null,p_provider:provider||null});if(error)throw error;location.replace('./pending.html')}
for(const b of document.querySelectorAll('[data-provider]'))b.onclick=async()=>{error.style.display='none';const provider=b.dataset.provider;b.disabled=true;try{const redirectTo=new URL('./register.html?oauth=1',location.href).href;const{error:e}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo}});if(e)throw e}catch(e){showError((String(e?.message||'').includes('provider')?'Этот способ входа ещё не подключён администратором. ': '')+(e?.message||'Не удалось открыть авторизацию.'));b.disabled=false}};
$('form').onsubmit=async e=>{e.preventDefault();error.style.display='none';success.style.display='none';const password=$('password').value;if(password!==$('password2').value)return showError('Пароли не совпадают.');submit.disabled=true;submit.textContent='Создаём аккаунт…';try{const full_name=$('fullName').value.trim(),phone=$('phone').value.trim(),email=$('email').value.trim().toLowerCase();const emailRedirectTo=new URL('./register.html?confirm=1',location.href).href;const{data,error:e}=await supabase.auth.signUp({email,password,options:{emailRedirectTo,data:{full_name,phone,staff_registration:true}}});if(e)throw e;if(data.session){await submitRequest('email')}else showSuccess('Аккаунт создан. Откройте письмо на указанном email и подтвердите регистрацию.')}catch(e){showError(e?.message||'Не удалось зарегистрироваться.')}finally{submit.disabled=false;submit.textContent='Зарегистрироваться'}};
(async()=>{try{const{data:{session}}=await supabase.auth.getSession();if(!session)return;const q=new URLSearchParams(location.search);if(q.get('oauth')==='1'||q.get('confirm')==='1'){const provider=session.user?.app_metadata?.provider||'email';await submitRequest(provider);return}await goByProfile()}catch(e){showError(e?.message||'Не удалось завершить регистрацию.')}})();
